### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [tokuhirom/jailingo#1]
First of all, thanks for creating and sharing a nice software!

Could you add LICENSE file?
The following page may help for choosing a license.
[Choose an open source license - Choose a License](http://choosealicense.com/)

I hope you choose a permissive license like MIT or Apache v2.
Thanks!

**Comment by tokuhirom** [comment]
Oops. I forgot it. I applied MIT license, thanks.

**Comment by hnakamur** [comment]
Thanks!
